### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by duongvtt96** [xbiome/protein-annotation#2]
Hi,
I am running po2vec to obtain GO embeddings for a custom set, but got memory issue. May be it comes from the con_pair_dataset step, even I decreased the number of negatives to 2. Do you have any recommendations?
Thank you.

**Comment by CNwangbin** [comment]
Hi,

Thank you for your feedback. Regarding the memory issue you're encountering while running po2vec, I have some suggestions for you.

Upon checking, I didn't find any obvious bugs in the code when running `train.py` as is. The memory problem is likely due to the significant memory required to build the `con_pair_dataset`, which can use around 35GB of memory in my runs.

Therefore, I recommend trying to run the code on a machine with more memory available, or consider optimizing the data loading and processing steps to reduce memory usage.
